name = "angelm/wolfram-oracle"
version = "0.0.0"
compiler = "v1.1.19"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'angelm/wolfram-oracle'"

[repository]
user = "angelm"
project = "wolfram-oracle"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[[dependencies]]
name = "sidan-lab/vodka"
version = "0.1.22"
source = "github"

[config]
